robot_base:
  steering_motor_port: /dev/ttyACM2
  driving_motor_port: /dev/ttyACM1
  max_driving_speed: 1.0
  max_steering_angle: 1.57
  driving_deadzone: 0.005
  steering_deadzone: 0.005
control:
  user_input:
    type: rc_receiver # joystick or rc_receiver
    joystick:
      device: /dev/input/event21
    rc_receiver:
      port: /dev/ttyACM0
      mapping:
        mode:
          channel: 5
          min: 172
          neutral: 1000
          max: 1811
          invert: true
        linear_y:
          channel: 2
          min: 172
          neutral: 992
          max: 1811
          invert: true
        linear_x:
          channel: 1
          min: 172
          neutral: 967
          max: 1806
          invert: false
        angular_z:
          channel: 3
          min: 172
          neutral: 980
          max: 1811
          invert: false
  command_regulation:
    max_steering_error: 3.14
    driving_limiting_scale: 0.5
  manual_mode:
    driving_scale: 1.0
    steering_scale: 1.5
  auto_mode:
    driving_scale: 1.0
    steering_scale: 1.0
